#!/usr/bin/env python3
"""Checks the translation files and builds the module the connector uses.

One file per language in this folder: <code>.json, with the same keys as en.json.
English is the fallback: a missing key shows the English text, so a new language
can start small. A key whose {placeholders} differ from English is an error.

Writes ../testplattform/public/felles/locales.js (all namespaces except «site»,
which the website build reads directly, and «pages»), renders the page templates in
templates/ for every language (the AI check at _meta.check_path, or <url_prefix>check/)
and prints how complete each language is.

Usage: python3 locales/build_locales.py [--strict]
  --strict: also fail when a language misses keys (used for nb, which must be complete)
"""
import html
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE.parent / "connector" / "public" / "felles" / "locales.js"
PUBLIC = HERE.parent / "connector" / "public"
COMPLETE = {"en", "nb"}  # languages that must have every key


def flatten(d, prefix=""):
    out = {}
    for k, v in d.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict) and not k.startswith("_"):
            out.update(flatten(v, key + "."))
        elif not k.startswith("_"):
            out[key] = v
    return out


def placeholders(v):
    return sorted(set(re.findall(r"\{(\w+)\}", v))) if isinstance(v, str) else []


def merged(base, own):
    out = dict(base)
    for k, v in own.items():
        out[k] = merged(base.get(k, {}), v) if isinstance(v, dict) and isinstance(base.get(k), dict) else v
    return out


# The texts the check page script needs at run time, with English filling the gaps.
CHECK_KEYS = ("profileName", "profileSource", "keyNames", "openNames", "checkNames", "yes", "no", "noActions",
              "notApplicable", "robotsLine", "robotsPresent", "robotsMissing", "botsNone")


def check_path(meta):
    return meta.get("check_path") or meta["url_prefix"] + "check/"


def render_check(locales):
    tpl = (HERE / "templates" / "check.html").read_text()
    written = []
    for code, data in locales.items():
        d = merged(locales["en"], data)
        meta, t = d["_meta"], d["pages"]["check"]
        others = [(c, locales[c]["_meta"]) for c in locales if c != code]
        alternates = "\n".join(f'<link rel="alternate" hreflang="{m["html_lang"]}" href="{check_path(m)}">' for _, m in [(code, meta), *others])
        languages = "".join(f' · <a href="{check_path(m)}" hreflang="{m["html_lang"]}" lang="{m["html_lang"]}">{html.escape(m["name"])}</a>' for _, m in others)
        texts = json.dumps({"page": t, "check": {k: d["check"][k] for k in CHECK_KEYS}}, ensure_ascii=False).replace("</", "<\\/")
        values = {"alternates": alternates, "languages": languages, "texts": texts}
        def sub(m):
            key = m.group(1)
            if key in values:
                return values[key]
            ns, name = key.split(".", 1)
            v = (meta if ns == "_meta" else t)[name]
            # Page texts may hold <code> and <strong>; attribute values are escaped.
            return html.escape(v) if name in ("title", "description", "urlPlaceholder", "yardstick", "appName") else v
        out = PUBLIC / check_path(meta).strip("/") / "index.html"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(re.sub(r"\{\{([\w.]+)\}\}", sub, tpl))
        written.append(check_path(meta))
    return written


def main():
    locales = {p.stem: json.loads(p.read_text()) for p in sorted(HERE.glob("*.json"))}
    en = flatten(locales["en"])
    errors, report = [], []
    for code, data in locales.items():
        meta = data.get("_meta", {})
        for field in ("code", "name", "html_lang", "site_dir", "url_prefix"):
            if field not in meta:
                errors.append(f"{code}: _meta.{field} is missing")
        flat = flatten(data)
        missing = [k for k in en if k not in flat]
        extra = [k for k in flat if k not in en]
        for k, v in flat.items():
            if k in en and placeholders(v) != placeholders(en[k]):
                errors.append(f"{code}: {k} has placeholders {placeholders(v)}, English has {placeholders(en[k])}")
        if extra:
            errors.append(f"{code}: keys not in en.json: {', '.join(extra[:5])}")
        if missing and code in COMPLETE:
            errors.append(f"{code}: {len(missing)} keys missing, for example {missing[0]}")
        done = round(100 * (len(en) - len(missing)) / len(en))
        report.append(f"{code:6} {meta.get('name', ''):12} {done:3} %  ({len(en) - len(missing)} of {len(en)} keys)")
    connector = {code: {k: v for k, v in data.items() if k not in ("site", "pages")} for code, data in locales.items()}
    OUT.write_text(
        "// Generated by locales/build_locales.py from locales/*.json. Do not edit.\n"
        "// Every user-facing text in the connector, the AI check and the business card generator.\n"
        f"export const LOCALES = {json.dumps(connector, ensure_ascii=False, indent=1)};\n"
    )
    pages = render_check(locales)
    print("\n".join(report))
    print("Rendered the AI check at " + ", ".join(pages))
    print(f"Wrote {OUT.relative_to(HERE.parent.parent)}")
    if errors:
        print("\nErrors:\n" + "\n".join(errors))
        sys.exit(1)


if __name__ == "__main__":
    main()
